       /* In this file I have put the text content */
$(document).ready(function () {
            $(getContent = function () {
                var dialogs = [
                    {
                        questions: ['Receivables are a result of timing difference between manufacturing the product or providing the service and receiving the compensation for that. ', 'Improving the turnover of receivables (net sales divided by receivables) is always a good target. The amount of receivables can grow when the business grows but the turnover of receivables (Net sales divided by receivables ) should not be negatively affected. ', 'Accounts receivable can also be decreased by sending invoices late or providing aggressive cash discounts for quick payments. ']
                        , trueAnswers: ['Correct! This statement is true. This timing difference can be decreased by establishing shorter payment terms for our sales and partly offset by asking for down payment and progress payments from the customers. ', 'Correct! This statement is true. Proactive management of receivables, especially overdue receivables, is a good standard management practice. An increase in receivables can be a sign of relaxed sales terms, poor collection, or a higher risk of customer default. The challenge is to make sure the level of receivables is appropriate given the companys industry and competitive strategy. ', 'Correct! This statement is not true. In theory this results in smaller accounts receivable but sending invoices late or offering aggressive cash discounts is the wrong way to do it as it hurts both the cash flow and profitability of the company! ']
                        , wrongAnswers: ['Incorrect. This statement is true. This timing difference can be decreased by establishing shorter payment terms for our sales and partly offset by asking for down payment and progress payments from the customers. ', 'Incorrect. This statement is true. Proactive management of receivables, especially overdue receivables, is a good standard management practice. An increase in receivables can be a sign of relaxed sales terms, poor collection, or a higher risk of customer default. The challenge is to make sure the level of receivables is appropriate given the companys industry and competitive strategy. ', 'Incorrect. This statement is not true. In theory this results in smaller accounts receivable but sending invoices late or offering aggressive cash discounts is the the wrong way to do it as it hurts both the cash flow and profitability of the company! ']
                }
                , {
                        questions: ['A key reason for a company to keep inventories is to secure availability when own production or customers have a need. ', 'One of the basic targets in inventory management is just-in-time arrival of raw material and components simultaneously securing the availability. ', 'The target should always be minimizing the inventory. ']
                        , trueAnswers: ['Correct! This statement is true. Other reasons for a company to keep inventories are also to take advantage of economies of scale in purchasing, production and transportation. However, in order to avoid overstocking, we have to establish service levels which define how quickly we target to fulfill the needs of our customers and own production. ', 'Correct! This statement is true. Other basic targets are shortest possible lead times from order to delivery and optimized levels of parts and finished goods inventories, while maintaining the targeted service levels, and minimal number of physical inventory locations while meeting the availability needs of the customers. ', 'Correct! This statement is not true. You should naturally minimize <b>excess</b> inventory. However, inventory is needed and the optimal level varies depending on e.g. the agreed service levels, the cost of procurement and the criticality of the components. ']
                        , wrongAnswers: ['Incorrect. This statement is true. Other reasons for a company to keep inventories are also to take advantage of economies of scale in purchasing, production and transportation. However, in order to avoid overstocking, we have to establish service levels which define how quickly we target to fulfill the needs of our customers and own production. ', 'Correct! This statement is true. Other basic targets are shortest possible lead times from order to delivery and optimized levels of parts and finished goods inventories, while maintaining the targeted service levels, and minimal number of physical inventory locations while meeting the availability needs of the customers. ', 'Incorrect. This statement is true. Other basic targets are shortest possible lead times from order to delivery and optimized levels of parts and finished goods inventories, while maintaining the targeted service levels, and minimal number of physical inventory locations while meeting the availability needs of the customers. ']
                }
                , {
                        questions: ['Payables have a major impact on Net Working Capital. ', 'The goal in managing payables is to originally negotiate as long payment terms as possible provided that we don’t have to pay higher price for the purchases because of these longer payment terms. ', 'Extending payment times by delaying the payments beyond due dates is good management practice. ']
                        , trueAnswers: ['Correct! This statement is true. Payables have a major impact on NWC because the ability to negotiate long payment terms for all procured materials, components and services and to maintain high payables (without extra cost) can finance a considerable part of inventory. For example, if we are able to stretch out our payments to suppliers without cost (we pay invoices in 60 days rather than 30 without additional cost), we can considerably decrease our working capital and thereby our bank debt. ', 'Correct! This statement is true. The longer the payment times are the bigger part of the inventories is financed by the suppliers. Long payment terms are always a sign of strong purchasing leverage. ', 'Correct! This statement is not true. Extending payment times by delaying the payments beyond due dates may lead to paying high interest costs on late payments and deterioration of your supplier relationship.']
                        , wrongAnswers: ['Incorrect. This statement is true. Payables have a major impact on NWC because the ability to negotiate long payment terms for all procured materials, components and services and to maintain high payables (without extra cost) can finance a considerable part of inventory. For example, if we are able to stretch out our payments to suppliers without cost (we pay invoices in 60 days rather than 30 without additional cost), we can considerably decrease our working capital and thereby our bank debt. ', 'Incorrect. This statement is true. The longer the payment times are the bigger part of the inventories is financed by the suppliers. Long payment terms are always a sign of strong purchasing leverage. ', 'Incorrect. This statement is not true. Extending payment times by delaying the payments beyond due dates may lead to paying high interest costs on late payments and deterioration of your supplier relationship. ']
                }
                , {
                        questions: ['Advances are used to cover the financing recuirements of a delivery and potential default risk of the customer. ', 'company’s basic principle is to ask for down payments only with large projects. ', 'Advances received decrease the need for other collaterals/guarantees.']
                        , trueAnswers: ['Correct! This statement is true. Advances received are a way to help the company (supplier) to finance the capital tied to Work-In-Process (WIP) in project deliveries, which are typically far customized. Furthermore, especially in large projects which have a long lead time, the circumstances of the project or the buyer can change and it is important that we as the supplier secured our position throughout the project. ', 'Correct! This statement is not true. Asking for down payments is important also with smaller deliveries especially when talking about customized solutions. ', 'Correct! This statement is true. Advances received also considerably decrease companys risk as the supplier in case of a default by our customer. ']
                        , wrongAnswers: ['Incorrect. This statement is true. Advances received are a way to help the company (supplier) to finance the capital tied to Work-In-Process (WIP) in project deliveries, which are typically far customized. Furthermore, especially in large projects which have a long lead time, the circumstances of the project or the buyer can change and it is important that we as the supplier secured our position throughout the project. ', 'Incorrect. This statement is not true. Asking for down payments is important also with smaller deliveries especially when talking about customized solutions. ', 'Incorrect. This statement is true. Advances received also considerably decrease companys risk as the supplier in case of a default by our customer. ']
                }
            ];
                var choices = ['Accounts recievable', 'Accounts payable ', 'Advances received ', 'Inventory '];
                var descriptions = ['<p> Refers to the money our customers owe to us in exchange for the products and services we have sold and provided. They are funds which we have earned but not yet collected. They typically increase when the business grows. </p>', '                        <p> Refers to the quantity of goods and materials company has in stock. Inventory usually consists of four main elements:</p> <ul class="list">                            <li>Raw Materials and Components</li>                            <li>Work-In-Process (WIP)</li>                             <li>Finished Goods</li>                             <li>Spare Parts and Consumables</li>                         </ul>                         <p>Inventories tend to increase when business grows but the turnover of inventories (Net sales divided by inventories or Cost Of Goods Sold divided by inventories) should not be negatively affected. </p>', '                        <p> Represents the money we owe to our suppliers in exchange for material, components, services and various supplies received. They are the funds we owe but have not yet paid, and they typically increase as the business grows. </p>', '                        <p> Represents the money we have received in advance from our customer in exchange for the products and services we have committed to deliver. They are funds we have received but not yet earned. </p>'];
                var headerP1 = ['What is Net Working Capital (NWC)? ', 'Core components of Net Working Capital ', 'Companies gather funds from equity and debt markets to finance capital tied to their operations in form of cash and liquid assets, fixed assets and net working capital – if net working capital increases typically the company needs to borrow more money.'];
                var headerP2 = ['What is Net Working Capital (NWC)? ', 'Core components of Net Working Capital', 'The main components of NWC are described on the chart below. Drag components of NWC from below the graph to corresponding descriptions. ', 'Net Working Capital', 'You will also be given statements concerning all components and your task is to choose whether the statement is true or false.'];

                return {
                    dialogs: dialogs
                    , choices: choices
                    , descriptions: descriptions,
                    headerP2:headerP2,
                    headerP1:headerP1

                };
            });
        });